/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 卡片名称
 */
export enum FormName {
  // 默认卡片
  DEFAULT = 'default',
  // 2x2 日程卡片
  AGENDA_CARD_2X2 = 'AgendaCard2x2',
  // 2x4 日程卡片
  AGENDA_CARD_2X4 = 'AgendaCard2x4',
  // 4x4 日程卡片
  AGENDA_CARD_4X4 = 'AgendaCard4x4',
  // 4x6 周内日程卡片
  AGENDA_CARD_4X6 = 'AgendaCard4x6',
  // 2X2 月视图卡片
  MONTH_CARD_2X2 = 'MonthCard2x2',
  // 4X4 月视图卡片
  MONTH_CARD_4X4 = 'MonthCard4x4',
  // 2x2 重要日卡片
  IMPORTANT_CARD_2X2 = 'ImportantCard2x2',
  // 2x4 重要日卡片
  IMPORTANT_CARD_2X4 = 'ImportantCard2x4'
}
