/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const MIN_WINDOW_WIDTH_VP = 660; //需要分屏的屏幕宽度

export const MIN_WINDOW_HEIGHT_VP = 300; //需要隐藏菜单的高度

export const MIDDLE_WINDOW_WIDTH_VP = 840; //折叠屏展开态屏幕宽度

export const MIN_WINDOW_SPLIT_SCREEN_WIDTH_VP = 520; // PC 分屏-系统设置显示大小在最大档

export const MIN_WINDOW_SHEET_BOTTOM = 600; // 半模态在不同窗口所支持的显示类型：1. 宽度 < 600vp：底部。