/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * db 首选项文件中的key
 */

export enum DbStoreKeys {

  /**
   * CalendarDb 的版本key
   */
  CALENDAR_DB_VERSION_KEY = 'calendar_db_version_key',

  /**
   * PushDb 的版本key
   */
  PUSH_DB_VERSION_KEY = 'push_db_version_key'
}