/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum MigrateFromEventDataKeys {

  /**
   * 迁移event data的key
   */
  MIGRATE_EVENT_DATA_KEY = 'MigrateEventDataKey',

  /**
   * 迁移重要日卡片信息的key
   */
  MIGRATE_FORM_INFO_KEY = 'MigrateFormInfosKey',


  /**
   * 迁移卡片信息的key
   */
  MIGRATE_BASE_FORM_INFO_KEY = 'MigrateBaseFormInfosKey',

  /**
   * 迁移授权信息的key
   */
  MIGRATE_IS_AGREE = 'MigrateIsAgree',
}